"""Initial migration

Revision ID: bbad4e384bb9
Revises: 
Create Date: 2025-11-17 01:16:41.319282

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bbad4e384bb9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('trades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('buy_date', sa.DateTime(), nullable=True),
    sa.Column('sell_date', sa.DateTime(), nullable=True),
    sa.Column('profit_loss_rate', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trades_id'), 'trades', ['id'], unique=False)
    op.create_index(op.f('ix_trades_ticker'), 'trades', ['ticker'], unique=False)
    op.create_table('review_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('trade_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('final_memo', sa.String(), nullable=True),
    sa.Column('subjective_memo', sa.String(), nullable=True),
    sa.Column('emotion_tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('chart_context', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('news_context', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('market_context', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('financial_context', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ai_analysis', sa.String(), nullable=True),
    sa.Column('ai_questions', sa.String(), nullable=True),
    sa.Column('primary_type', sa.String(), nullable=True),
    sa.Column('secondary_type', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['trade_id'], ['trades.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trade_id')
    )
    op.create_index(op.f('ix_review_notes_id'), 'review_notes', ['id'], unique=False)
    op.create_index(op.f('ix_review_notes_primary_type'), 'review_notes', ['primary_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_review_notes_primary_type'), table_name='review_notes')
    op.drop_index(op.f('ix_review_notes_id'), table_name='review_notes')
    op.drop_table('review_notes')
    op.drop_index(op.f('ix_trades_ticker'), table_name='trades')
    op.drop_index(op.f('ix_trades_id'), table_name='trades')
    op.drop_table('trades')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###

